### ISSUE TITLE
How to train the model with my own data ? Can you please create an example for train data struct?

### ISSUE THREAD

**Issue by liuchangf** [MaybeShewill-CV/CRNN_Tensorflow#262]
Great Job!

As title,  Can you please create an example for train data struct ? Such like : how to store labels , with xml ? csv ? or sth else ... , and what the data dir should be ? one folder for images and another for labels etc... ?

**Comment by MaybeShewill-CV** [comment]
@liuchangf You could organize your data according to the synth90k dataset's format and reuse the data feed pip line I pushed here:)

**Comment by liuchangf** [comment]
Hello:
         how to keep training from your shared model, I want to try if it is possible to perform transfer learning on this model ?

**Comment by MaybeShewill-CV** [comment]
@liuchangf You could find the solution in README file:)

**Comment by sirius0503** [comment]
@MaybeShewill-CV : If we are doing transfer learning with the pretrained model, we should normally freeze up the conv-base and then, make a few of the last few layers trainable. Also, then we should be able to train our model on our own dataset of , say 250-1000 images? Am I right about this, can I train the model by following Synth90k directory structure, and transfer learning will happen as given in the readme, by using pretrained weights. Also, about the number of images, I saw in a different thread that you had used ~1 million images, so that makes me even confused.
